name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure local directory exists
        run: mkdir -p Task/Task_Backend

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TASK_BACKENDSECRET }}

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Pull latest changes from master
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-34-205-29-69.compute-1.amazonaws.com 'cd /home/ec2-user/Task/Task_Backend && git pull origin master'

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no Dest/Dest_backend ec2-user@ec2-34-205-29-69.compute-1.amazonaws.com:/home/ec2-user/Task/Task_Backend

      - name: Install dependencies
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-34-205-29-69.compute-1.amazonaws.com 'cd /home/ec2-user/Task/Task_Backend && npm install'

      - name: Restart PM2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-34-205-29-69.compute-1.amazonaws.com 'cd /home/ec2-user/Task/Task_Backend && pm2 start app.js'